<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Bis-Mac-mini.local" failures="2" tests="6" name="TestCases.TS003_HomeScripts03" time="734.883" errors="0" timestamp="19 Nov 2018 22:50:45 GMT" skipped="0">
  <testcase classname="TestCases.TS003_HomeScripts03" name="TS003_HomeScripts03_Home1_checkCollectionOnTopAfterEditCollection" time="85.748">
    <failure message="Test case is failed - Bug 26325 " type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Test case is failed - Bug 26325 
	at org.testng.Assert.fail(Assert.java:93)
	at TestCases.TS003_HomeScripts03.TS003_HomeScripts03_Home1_checkCollectionOnTopAfterEditCollection(TS003_HomeScripts03.java:88)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:72)
	at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:123)
]]>
    </failure>
  </testcase> <!-- TS003_HomeScripts03_Home1_checkCollectionOnTopAfterEditCollection -->
  <testcase classname="TestCases.TS003_HomeScripts03" name="TS003_HomeScripts03_Home2_checkCollectionOnTopAfterAddCollection" time="74.534">
    <failure message="Test case is failed - Bug 26325 " type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Test case is failed - Bug 26325 
	at org.testng.Assert.fail(Assert.java:93)
	at TestCases.TS003_HomeScripts03.TS003_HomeScripts03_Home2_checkCollectionOnTopAfterAddCollection(TS003_HomeScripts03.java:116)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:72)
	at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:123)
]]>
    </failure>
  </testcase> <!-- TS003_HomeScripts03_Home2_checkCollectionOnTopAfterAddCollection -->
  <testcase classname="TestCases.TS003_HomeScripts03" name="TS003_HomeScripts03_Home6_checkCollectionOnTopAfterMoveNote" time="118.643"/>
  <testcase classname="TestCases.TS003_HomeScripts03" name="TS003_HomeScripts03_Home5_checkCollectionOnTopAfterMoveContact" time="130.336"/>
  <testcase classname="TestCases.TS003_HomeScripts03" name="TS003_HomeScripts03_Home3_checkCollectionOnTopAfterMoveTodo" time="156.282"/>
  <testcase classname="TestCases.TS003_HomeScripts03" name="TS003_HomeScripts03_Home7_checkCollectionOnTopAfterMoveEmail" time="169.340"/>
</testsuite> <!-- TestCases.TS003_HomeScripts03 -->
